#ifndef StorageConstant_h
#define StorageConstant_h

/**
 * @brief this header class hold all the storage data length
 * 
 */

#define USERNAME_LENGTH 8
#define USERNAME_STORE_INDEX 0 

#define WIFI_NAME_LENGTH 20
#define WIFI_NAME_STORE_INDEX 10

#define WIFI_PASSWORD_LENGTH 20
#define WIFI_PASSWORD_STORE_INDEX 40

#define WIFI_ENABLED_LENGTH 1
#define WIFI_ENABLED_STORE_INDEX 70

#define DATA_TRANSMIT_ENABLED_LENGTH 1
#define DATA_TRANSMIT_ENABLED_STORE_INDEX 71

#define DATA_TRANSMIT_PERIOD_LENGTH 1
#define DATA_TRANSMIT_PERIOD_STORE_INDEX 72

#define SENSOR_MEASURE_PERIOD_LENGTH 1
#define SENSOR_MEASURE_PERIOD_STORE_INDEX 73

#define WATER_CONTROLLER_MODE_LENGTH 1
#define WATER_CONTROLLER_MODE_STORE_INDEX 74

#define HUMIDITY_MODE_MIN_HUMIDITY_LENGTH 1
#define HUMIDITY_MODE_MIN_HUMIDITY_STORE_INDEX 75
#define HUMIDITY_MODE_MAX_HUMIDITY_LENGTH 1
#define HUMIDITY_MODE_MAX_HUMIDITY_STORE_INDEX 76
#define HUMIDITY_MODE_TARGET_HUMIDITY_LENGTH 1
#define HUMIDITY_MODE_TARGET_HUMIDITY_STORE_INDEX 77

#define SCHEDULE_MODE_TARGET_HUMIDITY_LENGTH 1
#define SCHEDULE_MODE_TARGET_HUMIDITY_STORE_INDEX 78
#define SCHEDULE_MODE_DURATION_LENGTH 4
#define SCHEDULE_MODE_DURATION_STORE_INDEX 79

#define UserNameLength 8
#define TotalStorageSize 8


#endif