#ifndef StorageConstant_h
#define StorageConstant_h

/**
 * @brief this header class hold all the storage data length
 * 
 */

#define SETUP_CODE_LENGTH 3
#define SETUP_CODE_STORE_INDEX 0
#define SETUP_CODE_0 56
#define SETUP_CODE_1 88
#define SETUP_CODE_2 48

#define STORE_VERSION_LENGTH 1
#define STORE_VERSION_STORE_INDEX 4

#define IS_BEGIN_SYSTEM_RESET_LENGTH 1
#define IS_BEGIN_SYSTEM_RESET_STORE_INDEX 5

#define IS_USERNAME_SET_LENGTH 1
#define IS_USERNAME_SET_STORE_INDEX 6

#define IS_ACCESS_POINT_SET_LENGTH 1
#define IS_ACCESS_POINT_SET_STORE_INDEX 7

#define USERNAME_LENGTH 8
#define USERNAME_STORE_INDEX 10 

#define WIFI_NAME_LENGTH 20
#define WIFI_NAME_STORE_INDEX 20

#define WIFI_PASSWORD_LENGTH 20
#define WIFI_PASSWORD_STORE_INDEX 50

#define WIFI_ENABLED_LENGTH 1
#define WIFI_ENABLED_STORE_INDEX 80

#define DATA_TRANSMIT_ENABLED_LENGTH 1
#define DATA_TRANSMIT_ENABLED_STORE_INDEX 81

#define DATA_TRANSMIT_PERIOD_LENGTH 1
#define DATA_TRANSMIT_PERIOD_STORE_INDEX 82 

#define SENSOR_MEASURE_PERIOD_LENGTH 1
#define SENSOR_MEASURE_PERIOD_STORE_INDEX 83 

#define WATER_CONTROLLER_MODE_LENGTH 1
#define WATER_CONTROLLER_MODE_STORE_INDEX 84

#define HUMIDITY_MODE_MIN_HUMIDITY_LENGTH 1
#define HUMIDITY_MODE_MIN_HUMIDITY_STORE_INDEX 85
#define HUMIDITY_MODE_MAX_HUMIDITY_LENGTH 1
#define HUMIDITY_MODE_MAX_HUMIDITY_STORE_INDEX 86
#define HUMIDITY_MODE_TARGET_HUMIDITY_LENGTH 1
#define HUMIDITY_MODE_TARGET_HUMIDITY_STORE_INDEX 87

#define SCHEDULE_MODE_TARGET_HUMIDITY_LENGTH 1
#define SCHEDULE_MODE_TARGET_HUMIDITY_STORE_INDEX 88
#define SCHEDULE_MODE_DURATION_LENGTH 4
#define SCHEDULE_MODE_DURATION_STORE_INDEX 89

#define MANUAL_MODE_TURN_ON_DURATION_LENGTH 1
#define MANUAL_MODE_TURN_ON_DURATION_STORE_INDEX 93

#define LAST_WATER_TIME_LENGTH 4
#define LAST_WATER_TIME_STORE_INDEX 94

#define STORAGE_COVER_RANGE 100

#endif